spring.application.name=aiproject

spring.datasource.url=jdbc:mysql://localhost:3306/projectAi
spring.datasource.username=root
spring.datasource.password=1109
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# \u274C REMOVE H2 (DO NOT USE WITH MYSQL)
# spring.h2.console.enabled=true

# ===============================

# JWT
# ===============================
jwt.secret=MySuperSecretJwtKey123456789
jwt.expiration=86400000

# ===============================
# EMAIL (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=blackaibc@gmail.com
spring.mail.password=byfd owom nwid rmpn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# SMS (FAST2SMS)
# ===============================
fast2sms.api.key=zYgbXNlQtfiPLBjd4h568IKrUEyu1ZOcm79a3RHVskAWvoxp2FpP4hoEdleMOKmXrYkDQITz8yjtxfLG
fast2sms.url=https://www.fast2sms.com/dev/bulkV

